import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Check, Clipboard, KeyRound, Plug, Plus, ShieldOff, X } from 'lucide-react';
import { ApiError, integrationsAdminApi, type IntegrationAppDto, type IntegrationScope } from '@/lib/api';
import { FolderPicker } from '@/components/files/FolderPicker';
import { PageTitle } from '@/components/ui/PageTitle';
import { EmptyState } from '@/components/ui/States';
import { formatRelativeTime } from '@/lib/utils';
import { activeCredentialCount, INTEGRATION_SCOPE_OPTIONS, integrationStatus } from '@/lib/integration-ui';

const SCOPES:IntegrationScope[]=INTEGRATION_SCOPE_OPTIONS;
export default function AdminIntegrationsPage(){
 const qc=useQueryClient(); const apps=useQuery({queryKey:['admin-integrations'],queryFn:integrationsAdminApi.list});
 const [createOpen,setCreateOpen]=useState(false); const [selected,setSelected]=useState<IntegrationAppDto|null>(null); const [secret,setSecret]=useState<string|null>(null); const [copied,setCopied]=useState(false);
 const refresh=()=>void qc.invalidateQueries({queryKey:['admin-integrations']});
 return <div className="space-y-4"><PageTitle title="Connected Apps" description="จัดการตัวตน API ขอบเขตโฟลเดอร์ และสิทธิ์ของระบบใน S2 Ecosystem" />
  <div className="flex justify-end"><button className="s2-btn s2-btn-primary" onClick={()=>setCreateOpen(true)}><Plus className="h-4 w-4"/>สร้างแอปเชื่อมต่อ</button></div>
  {apps.data?.data.length===0?<div className="rounded-2xl border border-line bg-surface"><EmptyState compact icon={<Plug className="h-6 w-6"/>} title="ยังไม่ได้เชื่อมต่อ" description="สร้าง Connected App และกำหนดขอบเขตโฟลเดอร์ก่อนออก Credential"/></div>:null}
  <div className="grid gap-3 xl:grid-cols-2">{apps.data?.data.map(app=><article key={app.id} className="rounded-2xl border border-line bg-surface p-4 shadow-subtle"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-50 text-brand-600"><Plug className="h-5 w-5"/></span><div className="min-w-0 flex-1"><h2 className="font-semibold text-navy-900">{app.name}</h2><p className="text-[11px] text-navy-400">{app.code}</p></div><span className={`rounded-full px-2 py-1 text-[10px] ${integrationStatus(app).code==='ACTIVE'?'bg-emerald-50 text-emerald-700':'bg-navy-50 text-navy-500'}`}>{integrationStatus(app).label}</span></div><dl className="mt-4 grid grid-cols-2 gap-2 text-[11.5px]"><dt className="text-navy-400">Allowed folder</dt><dd className="text-right text-navy-700">{app.allowedRoot.name}</dd><dt className="text-navy-400">Credentials</dt><dd className="text-right text-navy-700">{activeCredentialCount(app)}</dd><dt className="text-navy-400">ใช้ล่าสุด</dt><dd className="text-right text-navy-700">{app.lastUsedAt?formatRelativeTime(app.lastUsedAt):'ยังไม่เคยใช้'}</dd></dl><div className="mt-3 flex flex-wrap gap-1">{app.scopes.map(s=><span key={s} className="rounded-md border border-line px-1.5 py-0.5 text-[9.5px] text-navy-500">{s}</span>)}</div><div className="mt-4 flex gap-2"><button className="s2-btn s2-btn-outline" onClick={()=>setSelected(app)}>รายละเอียด</button><button className="s2-btn s2-btn-primary" onClick={()=>void integrationsAdminApi.credential(app.id,'Admin created').then(r=>{setSecret(r.data.secret);refresh()})}><KeyRound className="h-4 w-4"/>สร้าง API Credential</button></div></article>)}</div>
  {createOpen?<CreateDialog onClose={()=>setCreateOpen(false)} onDone={()=>{setCreateOpen(false);refresh()}}/>:null}
  {selected?<Details app={selected} onClose={()=>setSelected(null)} onChanged={()=>{setSelected(null);refresh()}}/>:null}
  {secret?<div className="fixed inset-0 z-[var(--z-dialog)] flex items-center justify-center bg-[var(--s2-overlay)] p-3"><section role="dialog" aria-modal="true" aria-labelledby="secret-title" className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-2xl border border-line bg-[var(--s2-elevated)] p-5 shadow-pop"><h2 id="secret-title" className="text-[16px] font-semibold text-navy-900">API Secret — แสดงครั้งเดียว</h2><p className="mt-2 rounded-xl bg-amber-50 p-3 text-[12px] text-amber-800">โปรดคัดลอก Secret นี้ทันที ระบบจะไม่สามารถแสดง Secret เดิมได้อีก</p><code className="mt-4 block break-all rounded-xl border border-line bg-[var(--s2-surface-soft)] p-3 text-[11px] text-navy-700">{secret}</code><div className="mt-4 flex justify-end gap-2"><button className="s2-btn s2-btn-outline" onClick={()=>void navigator.clipboard.writeText(secret).then(()=>setCopied(true))}><Clipboard className="h-4 w-4"/>{copied?'คัดลอกแล้ว':'คัดลอก'}</button><button className="s2-btn s2-btn-primary" onClick={()=>{setSecret(null);setCopied(false)}}>ฉันบันทึก Secret แล้ว</button></div></section></div>:null}
 </div>;
}

function CreateDialog({onClose,onDone}:{onClose:()=>void;onDone:()=>void}){const[name,setName]=useState('');const[code,setCode]=useState('');const[description,setDescription]=useState('');const[root,setRoot]=useState<string|null>(null);const[scopes,setScopes]=useState<IntegrationScope[]>(['resources:read','resources:create']);const[error,setError]=useState('');const mutation=useMutation({mutationFn:()=>integrationsAdminApi.create({name,code,description:description||null,allowedRootId:root!,scopes}),onSuccess:onDone,onError:e=>setError(e instanceof ApiError?e.message:'สร้างแอปไม่สำเร็จ')});return <div className="fixed inset-0 z-[var(--z-dialog)] flex items-center justify-center bg-[var(--s2-overlay)] p-3"><section role="dialog" aria-modal="true" aria-labelledby="create-app-title" className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-2xl border border-line bg-[var(--s2-elevated)] p-5 shadow-pop"><div className="flex"><h2 id="create-app-title" className="flex-1 text-[16px] font-semibold text-navy-900">สร้างแอปเชื่อมต่อ</h2><button aria-label="ปิด" onClick={onClose}><X className="h-4 w-4"/></button></div><form className="mt-4 space-y-4" onSubmit={e=>{e.preventDefault();mutation.mutate()}}><label className="block text-[11.5px] font-semibold">ชื่อ<input className="s2-input mt-1.5" value={name} onChange={e=>setName(e.target.value)} required/></label><label className="block text-[11.5px] font-semibold">Code<input className="s2-input mt-1.5 uppercase" value={code} onChange={e=>setCode(e.target.value)} placeholder="S2_PAYROLL" required/></label><label className="block text-[11.5px] font-semibold">คำอธิบาย<textarea className="s2-input mt-1.5 min-h-20" value={description} onChange={e=>setDescription(e.target.value)}/></label><div><p className="mb-1.5 text-[11.5px] font-semibold">Allowed folder</p><FolderPicker value={root} onChange={setRoot} driveRoot="MY_DRIVE" onDriveRootChange={() => undefined} selectableDriveRoots={["MY_DRIVE"]} disabledDriveReason="แอปเชื่อมต่อกำหนดปลายทางได้เฉพาะไดร์ฟของฉัน"/></div><fieldset><legend className="text-[11.5px] font-semibold">Scopes</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{SCOPES.map(s=><label key={s} className="flex items-center gap-2 text-[11px]"><input type="checkbox" checked={scopes.includes(s)} onChange={()=>setScopes(v=>v.includes(s)?v.filter(x=>x!==s):[...v,s])}/>{s}</label>)}</div></fieldset>{error?<p className="text-[11px] text-red-600">{error}</p>:null}<div className="flex justify-end gap-2"><button type="button" className="s2-btn s2-btn-ghost" onClick={onClose}>ยกเลิก</button><button className="s2-btn s2-btn-primary" disabled={!name.trim()||!code.trim()||!root||scopes.length===0||mutation.isPending}>{mutation.isPending?'กำลังสร้าง…':'สร้างแอป'}</button></div></form></section></div>}

function Details({app,onClose,onChanged}:{app:IntegrationAppDto;onClose:()=>void;onChanged:()=>void}){return <div className="fixed inset-0 z-[var(--z-dialog)] flex items-center justify-center bg-[var(--s2-overlay)] p-3"><section role="dialog" aria-modal="true" aria-labelledby="app-details-title" className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-2xl border border-line bg-[var(--s2-elevated)] p-5 shadow-pop"><div className="flex"><div className="flex-1"><h2 id="app-details-title" className="text-[16px] font-semibold">{app.name}</h2><p className="text-[11px] text-navy-400">{app.code}</p></div><button aria-label="ปิด" onClick={onClose}><X className="h-4 w-4"/></button></div><p className="mt-4 text-[12px]">Allowed folder: <b>{app.allowedRoot.name}</b></p><h3 className="mt-4 text-[12px] font-semibold">Credentials</h3><div className="mt-2 space-y-2">{app.credentials.length===0?<p className="text-[11px] text-navy-400">ยังไม่มี Credential</p>:app.credentials.map(c=><div key={c.id} className="flex items-center gap-2 rounded-xl border border-line p-3"><KeyRound className="h-4 w-4"/><div className="min-w-0 flex-1"><p className="truncate text-[11px]">{c.id}</p><p className="text-[9.5px] text-navy-400">{c.revokedAt?'เพิกถอนแล้ว':c.lastUsedAt?`ใช้ล่าสุด ${formatRelativeTime(c.lastUsedAt)}`:'ยังไม่เคยใช้'}</p></div>{!c.revokedAt?<button className="s2-btn border border-red-200 text-red-600" onClick={()=>void integrationsAdminApi.revoke(app.id,c.id).then(onChanged)}><ShieldOff className="h-4 w-4"/>เพิกถอน</button>:<Check className="h-4 w-4 text-navy-300"/>}</div>)}</div><div className="mt-4 flex justify-between"><button className="s2-btn s2-btn-outline" onClick={()=>void integrationsAdminApi.update(app.id,{isActive:!app.isActive}).then(onChanged)}>{app.isActive?'ปิดใช้งานแอป':'เปิดใช้งานแอป'}</button><button className="s2-btn s2-btn-primary" onClick={onClose}>ปิด</button></div></section></div>}
